name: Unit Test With Coverage
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0
    - name: Restore dependencies
      run: dotnet restore   
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test  -p:CollectCoverage=true -p:CoverletOutput=reports/ -p:CoverletOutputFormat=opencover --no-build --verbosity normal Calculator.Tests/
    - name: Create Test Coverage Badge
      uses: simon-k/dotnet-code-coverage-badge@v1.0.0
      id: create_coverage_badge
      with:
        label: Unit Test Coverage
        color: brightgreen
        path: Calculator.Tests/reports/coverage.opencover.xml
        gist-filename: code-coverage.json
        gist-id: b6721ff1778c73fd9cd2da610fb355a6
        gist-auth-token: ${{ secrets.GIST_AUTH_TOKEN }}       
    - name: Print code coverage
      run: echo "Code coverage percentage ${{steps.create_coverage_badge.outputs.percentage}}%"